#!/bin/sh
set -e

config=/etc/intelmq/contactdb-serve.conf

if [ "$1" = "configure" ] ; then
    if [ ! -e $config ] ; then
        python3 -m contactdb_api --example-conf >$config
    fi

    if ! getent passwd www-dbapi >/dev/null 2>&1; then
        useradd --system -s /usr/sbin/nologin -d /tmp www-dbapi
    fi

    . /usr/share/apache2/apache2-maintscript-helper
    apache2_invoke ensite db-api.conf
fi

#DEBHELPER#

