#Github Workflow to find and notify about misspellings
#
#SPDX-FileCopyrightText: 2020 IntelMQ Team
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Codespell spelling check"

on: [push, pull_request]

jobs:
  codespell:
    name: Find and notify about common misspellings
    runs-on: ubuntu-latest
    # This should not fail the whole workflow run
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install pip
      run: DEBIAN_FRONTEND=noninteractive sudo -E apt-get update -qq && DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y python3-pip
    - name: Install codespell
      run: pip3 install codespell
    - name: Run codespell
      run: codespell . docs/ -S './debian/*,./build/*,./.github,docs/_build' -x .github/workflows/codespell.excludelines -I .github/workflows/codespell.excludewords
