#SPDX-FileCopyrightText: 2023 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Build Debian packages"
on: [push, pull_request]

jobs:
  build-package:
    runs-on: ubuntu-20.04
    name: Build Debian packages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build package
      run: bash .github/workflows/scripts/debian-package.sh
